sonar.projectKey=patrici-a_snorlax-energy-geolocalization-service
sonar.projectName=snorlax-energy-geolocalization-service
sonar.organization=patrici-a
sonar.java.binaries=target/classes
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
